// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ColumnManagerController from "./column_manager_controller"
application.register("column-manager", ColumnManagerController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import JobStatusController from "./job_status_controller"
application.register("job-status", JobStatusController)
